[build]
  command = '''
    cd wedding_website
    pwd
    ls -la
    curl -sSL https://get.wasp-lang.dev/installer.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
    wasp version
    wasp build
  '''
  publish = "wedding_website/.wasp/build/web-app"

[build.environment]
  NODE_VERSION = "18"
